### ISSUE TITLE
DuplicatePlatformClasses warning during building the release

### ISSUE THREAD

**Issue by MatrosSkin** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#10]
## Expected Behavior
There should not be such warning or somewhere should be a note about that this warning is not critical and app built correctly. Also it would be great to have same behavior also during building development version.

## Actual Behavior
Only during building production release I see the message:
```
:packageRelease
:lintVitalReleaseplatforms/android/build.gradle:266: Error: json defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
    compile "org.json:json:20171018"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "DuplicatePlatformClasses":
   There are a number of libraries that duplicate not just functionality of
   the Android platform but using the exact same class names as the ones
   provided in Android -- for example the apache http classes. This can lead
   to unexpected crashes.

   To solve this, you need to either find a newer version of the library which
   no longer has this problem, or to repackage the library (and all of its
   dependencies) using something like the jarjar tool, or finally, rewriting
   the code to use different APIs (for example, for http code, consider using
   HttpUrlConnection or a library like okhttp.)

1 errors, 0 warnings
```
But the app lokks like still work correctly.

## Steps to Reproduce the Problem
Just build prod version

## Specifications

  - Plugin version: 0.0.6
  - Framework:
  - Framework version:
  - Operating system: ubuntu 18.04

**Comment by piotr-cz** [comment]
I think error descriptions says that it's safe to remove dependency `org.json:json:20171018` which is defined [here](https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics/blob/0.1.0/plugin.xml#L40) as it's already provided by Android OS.

**Comment by ReallySmallSoftware** [comment]
Thank you for this information.
