### ISSUE TITLE
Can I use it with google-firebase-plugin?

### ISSUE THREAD

**Issue by therepo90** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#14]
Im getting error:
 Cannot add extension with name 'crashlytics', as there is an extension already registered with that name.

**Comment by ReallySmallSoftware** [comment]
Didn't you already close a similar issue 12 days ago having determined that google-firebase-plugin already attempts to provide crashlytics support?

**Comment by therepo90** [comment]
Yep you right ;) Forgot to close it here as well. Cheers!
