### ISSUE TITLE
Property ANDROID_FIREBASE_VERSION undefined

### ISSUE THREAD

**Issue by Shantred** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#2]
I'm trying to implement Crashlytics in an existing Ionic 1 app using this cordova plugin, but running into the following error when trying to test via cordova run android:

> A problem occurred evaluating root project 'android'.
> Could not find property 'ANDROID_FIREBASE_VERSION' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@288172bb.

I installed using the provided command, including the firebase version and can see the variable at the bottom of my config.xml but am not able to actually get an android version to build.

**Comment by ReallySmallSoftware** [comment]
Sorry to hear you are having a problem. I'm afraid I'm not familiar with Ionic other than by general concept, but it sounds like the variable substitution isn't happening for some reason.

This post here for another plugin suggests a possible missing dependency:

[https://github.com/phonegap/phonegap-plugin-push/issues/2079](url)

And this one suggests editing the project.properties file for another similar issue:

[https://forum.ionicframework.com/t/could-not-get-unknown-property-google-play-services-version/114176](url)

Perhaps you could try the later and see if that helps, albeit not a proper solution to the problem?

**Comment by Jseekamp1** [comment]
I'm having the same issue with the newest version (0.0.5). Have you had any luck solving this issue @Shantred? 

Error Log - 
```
Could not get unknown property 'ANDROID_FIREBASE_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

config.xml - 
```
<plugin name="cordova-plugin-firebase-crashlytics" spec="0.0.5">
        <variable name="ANDROID_FIREBASE_VERSION" value="11.6.0" />
</plugin>
```

**Comment by ReallySmallSoftware** [comment]
@Jseekamp1 Are you using Ionic 1 like the original poster? If so were you able to try the links I suggested to him and if not can you give me more details about what you are using?

**Comment by Jseekamp1** [comment]
I'm using Ionic 1, and only one of the resolutions applied to me, and resulted in the same error. 
(Didn't apply: I do not have a com.google.android.gms:play-services-base:9.2.1 item in my project.properties file)
ionic info - 
```
  @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2
System:
    Node : v6.9.4
    npm  : 3.10.10 
    OS   : macOS Sierra
```
cordova-android: 6.2.3
FYI I have not included any other plugins that use firebase or push.

**Comment by tyrus1235** [comment]
@Jseekamp1 You misread the second link - you're actually supposed to change `com.google.firebase:firebase-core:` item to your Firebase version (mine was 11.0.1, for example).

**Comment by Jseekamp1** [comment]
I have tried several different versions including 11.0.1 and 11.6.0 (which I have tested and works for another plugin).

**Comment by tyrus1235** [comment]
@Jseekamp1 Well, I believe the version you need to use is the same as your other Firebase libs. If you don't have any Firebase libs listed on that file (aside from firebase-core), then I'm sorry but I don't know where you might find your firebase version. Perhaps through Ionic's CLI?

**Comment by ReallySmallSoftware** [comment]
Closing as no feedback for a while
