### ISSUE TITLE
Can't install the plugin with Phonegap & iOS

### ISSUE THREAD

**Issue by remcos** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#22]
## Expected Behavior
When building on Phonegap (build.phonegap.com), the plugin is added to the installable. 

## Actual Behavior
While the plugin is listed in the zip file I upload to Phonegap, it does not install. 
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.5, failed version requirement: >=5.0.0

## Steps to Reproduce the Problem

1. Create a phonegap configuration including the widget, with the latest phonegap version (cli-8.1.1)
2. Upload the phonegap configuration to build.phonegap.com

## Specifications

  - Plugin version: 0.0.9 & 0.1.0
  - Framework: Phonegap
  - Framework version: cli-8.1.1
  - Operating system: iOS

**Comment by ReallySmallSoftware** [comment]
I'm afraid as per the error message this plugin is only supported on cordova-ios 5.0.0 and above.
