### ISSUE TITLE
FirebaseCrashlytics plugin not been recognized by cordova ionic

### ISSUE THREAD

**Issue by eldelaguila77** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#23]
## Expected Behavior

Firebase crashlytics plugin need be recognized by cordova

## Actual Behavior

FirebaseCrashlytics plugin not been recognized by cordova

I am trying to use firebase crashlytics in ionic 4, but when i build my app this message is shown in the developer console in chrome, and firebase crashlytics is not working, I have already configurated the build.gradle and imported the google-service.json file.

![image](https://user-images.githubusercontent.com/8795417/57337928-9bcae600-70e8-11e9-9c68-4e61de0f3737.png)

The app builds successfully but firebase crashlytics plugin is not recognized by cordova

the console shows :

Install the FirebaseCrashlytics plugin: ‘ionic cordova plugin add cordova-plugin-firebase-crashlytics’

## Steps to Reproduce the Problem

I installed:

ionic cordova plugin add cordova-plugin-firebase-crashlytics
npm install @ionic-native/firebase-crashlytics

after, I imported the google-service.json file and configured the build.gradle, and build the app, but the developer console in chrome shows: **Install the FirebaseCrashlytics plugin: ‘ionic cordova plugin add cordova-plugin-firebase-crashlytics’**

## Specifications

  - Plugin version: 0.0.6
  - Framework: IONIC CORDOVA
  - Framework version: "@ionic-native/core": "^5.0.0",
    "@ionic-native/firebase-crashlytics": "^5.5.1",
   "@angular/core": "^7.2.2",
   "cordova-plugin-firebase-crashlytics": {
        "ANDROID_FIREBASE_CORE_VERSION": "16.0.0",
        "ANDROID_FIREBASE_VERSION": "11.8.0"
      }
  - Operating system: Ubuntu

**Comment by markamccorkle** [comment]
Good luck. lol. Nobody seems to respond and I still haven't found a working solution. I do wish ionic would remove plugins like this from their native list until someone verifies they actually work. 

One thing to try which got me further but didn't fix the plugin was to install `cordova-support-google-services`. This at least gets the plugin to say it's working but it just crashes when you actually try to use it. Both iOS and Android are not working for me with ionic 4. 

[https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics/issues/21](https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics/issues/21)

**Comment by piotr-cz** [comment]
This is somehow related to ionic and how it handles cordova plugins
I'd suggest to inspect where the message is coming from and debug ionic

**Comment by markamccorkle** [comment]
The ionic Native plugin has been updated and now installs but I still can't actually get the plugin to work. I still get the following when the app starts up. 
`Install the FirebaseCrashlytics plugin: 'ionic cordova plugin add cordova-plugin-firebase-crashlytics'`

**Comment by ReallySmallSoftware** [comment]
Apologies for not responding. Ionic is not something I have the time to support. I'm sorry this has caused you problems.
