### ISSUE TITLE
FirebaseCrashlytics is undefined

### ISSUE THREAD

**Issue by kalaiprakash93** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#26]
The following version i  have used in my app
![image](https://user-images.githubusercontent.com/19145824/60943746-7d5db280-a304-11e9-9959-a13960a1fd14.png)
<plugin name="cordova-plugin-firebase-crashlytics" spec="~0.1.0">
        <variable name="ANDROID_FIREBASE_CORE_VERSION" value="16.0.0" />
    </plugin>

Am calling below code in onDeviceReady event,
var crashlytics = FirebaseCrashlytics.initialise();
crashlytics.logException("my caught exception");

But it alwasys return  FirebaseCrashlytics is not defined error.
Am using phonegap online build.
Please check
![image](https://user-images.githubusercontent.com/19145824/60946111-f9f38f80-a30a-11e9-9081-930ad01b2dbc.png)

**Comment by kalaiprakash93** [comment]
While creating cordova build its working fine
but it is not working in Phonegap online build(build.phonegap.com)

**Comment by kalaiprakash93** [comment]
i got the issues and fixed.but in ios its not working

**Comment by svignesh07** [comment]
Hello @kalaiprakash93, I was wondering if you could get this plugin to work for iOS app? If yes, please let me know how you did it. Thanks.

**Comment by kalaiprakash93** [comment]
No.Its only working in android alone. not working in iOS
For iOS i have referred some other plugin
cordova-fabric-plugin

**Comment by svignesh07** [comment]
Got it. Thanks @kalaiprakash93. Also, could you please let me know if alternate plugin "cordova-fabric-plugin" you mentioned worked successfully for iOS?

**Comment by ReallySmallSoftware** [comment]
Someone has suggested there is some missing code in the iOS version - I am looking into this.

**Comment by MaxXx1313** [comment]
For android try to add the following plugin:
 `<plugin name="cordova-support-google-services" spec="1.3.1" />`

**Comment by ReallySmallSoftware** [comment]
I have published a new release as it was being asked for, but I haven't had time to test properly

**Comment by ReallySmallSoftware** [comment]
Closing as no response for a while

**Comment by MaxXx1313** [comment]
Sorry, I'd like to recommend using another plugin, which is more stable at the current moment: [firebase-x](https://github.com/dpa99c/cordova-plugin-firebasex)
