### ISSUE TITLE
[Ionic 4] Can't get it to work for iOS app.

### ISSUE THREAD

**Issue by svignesh07** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#27]
The plugin doesn't seem to work for iOS and I know the plugin isn't tested on iOS. 
What is happening for me is, the app crashes but the crash reports are NOT submitted to the Firebase. 
I followed all the steps mentioned and the app even crashes successfully (Test crash), but I don't see the communication happening between Firebase and my app. I don't see the Crashlytics dashboard for iOS app and instead I'm stuck at -- "Build and run your app". 

Has anybody got this plugin work for Ionic iOS app? 
Please let me know.
Thanks.

**Comment by piotr-cz** [comment]
I wasn't successful either.
I'm not using ionic.

**Comment by Darcelsan** [comment]
Same here... Anyone can help ?

**Comment by Darcelsan** [comment]
Hello, 
**I finally made it !** Dear @ReallySmallSoftware I've made a pull request to fix the bug !

You will also need to do a pod install and pod update to retrieve the pod libraries required but I advise you to make it automatic as suggested by the Ionic support here : [https://ionic.zendesk.com/hc/en-us/articles/360010049673-Managing-plugins-using-CocoaPods-in-Ionic-Appflow-](url) 

![Capture d’écran 2019-11-14 à 09 44 40](https://user-images.githubusercontent.com/10349529/68840776-abdd0700-06c3-11ea-902f-7078231e142b.png)

**Comment by nationdata-it** [comment]
if you can merge this pull request hopefully it will solve at least iOS issue.
https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics/pull/30
