### ISSUE TITLE
Example Documentation?

### ISSUE THREAD

**Issue by russcarver** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#4]
Can you put in your readme an example of how to use it?  I have the following:

`declare var FirebaseCrashlytics: any;`

and then later, trying to use as:

`FirebaseCrashlytics.crash();`

but I get an error: 

`"TypeError: FirebaseCrashlytics.crash is not a function"`

I chose "FirebaseCrashlytics" based on the `clobber` found in your `plugin.xml`.

**Comment by ReallySmallSoftware** [comment]
Sure, I'll add something - that was a bit of an oversight - sorry. Meanwhile, try this:

```
var crashlytics = FirebaseCrashlytics.initialise();

crashlytics.crash();
```

**Comment by russcarver** [comment]
That did it, thanks!

**Comment by ReallySmallSoftware** [comment]
Simple example above added to README

**Comment by Sahiltuteja** [comment]
unable to use in ionic 4 angular 6. Any suggestion ?
