### ISSUE TITLE
setUserIdentifier

### ISSUE THREAD

**Issue by russcarver** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#5]
When do you plan to support `setUserIdentifier` per the documentation at https://firebase.google.com/docs/crashlytics/customize-crash-reports ?

**Comment by ReallySmallSoftware** [comment]
I'm not honestly sure how I missed it! I have added it to my backlog and
expect I will look at it in the next few days.

**Comment by russcarver** [comment]
Do you have an updated ETA on adding this?

**Comment by ReallySmallSoftware** [comment]
I'm working on this now.

**Comment by ReallySmallSoftware** [comment]
This has now been added. Tested on iOS and Android.

**Comment by ReallySmallSoftware** [comment]
Closing as have not had any reported issues.
